# Generated by Django 4.2.5 on 2023-10-03 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_creatorusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorusername',
            name='creator',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='creators.creator'),
            preserve_default=False,
        ),
    ]
