# Generated by Django 4.2.5 on 2023-10-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('channel_id', models.CharField(max_length=30)),
                ('raw_json', models.TextField()),
            ],
        ),
    ]
