# Generated by Django 4.2.5 on 2023-10-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_channels', '0002_scraperesult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
