# Generated by Django 4.2.5 on 2023-10-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_channels', '0004_alter_channel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='etag',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='localized_title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='related_playlists',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
