# Generated by Django 4.2.5 on 2023-10-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yt_channels', '0005_alter_channel_description_alter_channel_etag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Channel', 'verbose_name_plural': 'Channels'},
        ),
        migrations.AlterModelOptions(
            name='channelstatistics',
            options={'verbose_name': 'Channel Statistic', 'verbose_name_plural': 'Channel Statistics'},
        ),
        migrations.AlterModelOptions(
            name='scraperesult',
            options={'verbose_name': 'Scrape Result', 'verbose_name_plural': 'Scrape Results'},
        ),
        migrations.AlterModelOptions(
            name='topiccategories',
            options={'verbose_name': 'Topic Category', 'verbose_name_plural': 'Topic Categories'},
        ),
    ]
