# Generated by Django 4.2.5 on 2023-10-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxies',
            options={'verbose_name': 'Proxy', 'verbose_name_plural': 'Proxies'},
        ),
    ]
