# Generated by Django 4.2.5 on 2023-10-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_alter_proxies_https_alter_proxies_ip_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proxies',
            new_name='Proxy',
        ),
    ]
