# Generated by Django 4.2.5 on 2023-10-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_rename_proxies_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='last_checked',
            field=models.DateTimeField(),
        ),
    ]
